### PR TITLE
Display recipes in db on home page 

### PR DESCRIPTION
**Pull request by joecai6**
# Resolves 
After creating your PR, please complete this template!

### What were your changes
- Changed some frontend code to fetch data from api
- added ingredient route and recipeIngredients model to get all ingredients from a recipe

### Todos
- need to fix config with server url
- better organization

Note: this is using localhost:3000 as the server endpoint.

### CODE REVIEW

**Comment by mingkaili** [comment]
I know you are still working on this, but just want to give you a fyi. you should not be creating a new ingredients route for the following reasons:
- You are meaningly doing it to replace https://github.com/cse112-group10/cse112-sp22-group10/blob/main/source/frontend/assets/components/RecipeDisplay.js#L443 
- Having a fetch call in that creates a huge overhead as there might be 100 recipes, and for each recipe, it will make a separate fetch request just to get the ingredients. This will drastically increase load time + resource waste on the site and it's error prone.
Instead you should make a GET /recipes/ generic route that fetches all recipes, and modify the recipes returned in the way frontend needs them. For this specific case, the data it's looking for has the following structure:
```
[
  {
    recipeId: 1
    .... 
    ingredientList: [
       ...
    ]
  }
]
```
A solution is to use joins between recipes table and ingredients table, then use js to reformat the array returned into the above type. (The implementation requires some looping through, etc, but it shouldn't be too hard). This will significantly reduce load time and avoids the need to create a whole new route just for the purpose of displaying all recipes.

**Comment by joecai6** [comment]
> I know you are still working on this, but just want to give you a fyi. you should not be creating a new ingredients route for the following reasons:
> 
> * You are meaningly doing it to replace https://github.com/cse112-group10/cse112-sp22-group10/blob/main/source/frontend/assets/components/RecipeDisplay.js#L443 which doesn't need that new route.
> * Having a fetch call in that creates a huge overhead as there might be 100 recipes, and for each recipe, it will make a separate fetch request just to get the ingredients. This will drastically increase load time + resource waste on the site and it's error prone.
> 
> Instead, since you are using
> 
> ```
>  fetch(`${url}/recipes/spiceRating/${spiceLevel}`)
>         .then(response => response.json())
>         .then(result => {
>           resolve(result);
>         })
>         .catch(error => {
>           reject(new Error('Could not get recipes.'));
>         });
> ```
> 
> you should modify a GET /recipes/spiceRating/:spiceLevel route by modify the recipes returned in the way frontend needs them. For this specific case, the data it's looking for has the following structure:
> 
> ```
> [
>   {
>     recipeId: 1
>     .... 
>     ingredientList: [
>        ...
>     ]
>   }
> ]
> ```
> 
> A solution is to use joins between recipes table and ingredients table, then use js to reformat the array returned into the above type. (The implementation requires some looping through, etc, but it shouldn't be too hard). This will significantly reduce load time and avoids the need to create a whole new route just for the purpose of displaying all recipes.



> I know you are still working on this, but just want to give you a fyi. you should not be creating a new ingredients route for the following reasons:
> 
> * You are meaningly doing it to replace https://github.com/cse112-group10/cse112-sp22-group10/blob/main/source/frontend/assets/components/RecipeDisplay.js#L443 which doesn't need that new route.
> * Having a fetch call in that creates a huge overhead as there might be 100 recipes, and for each recipe, it will make a separate fetch request just to get the ingredients. This will drastically increase load time + resource waste on the site and it's error prone.
> 
> Instead, since you are using
> 
> ```
>  fetch(`${url}/recipes/spiceRating/${spiceLevel}`)
>         .then(response => response.json())
>         .then(result => {
>           resolve(result);
>         })
>         .catch(error => {
>           reject(new Error('Could not get recipes.'));
>         });
> ```
> 
> you should modify a GET /recipes/spiceRating/:spiceLevel route by modify the recipes returned in the way frontend needs them. For this specific case, the data it's looking for has the following structure:
> 
> ```
> [
>   {
>     recipeId: 1
>     .... 
>     ingredientList: [
>        ...
>     ]
>   }
> ]
> ```
> 
> A solution is to use joins between recipes table and ingredients table, then use js to reformat the array returned into the above type. (The implementation requires some looping through, etc, but it shouldn't be too hard). This will significantly reduce load time and avoids the need to create a whole new route just for the purpose of displaying all recipes.

**Comment by mingkaili** [comment]
> Thanks for pointing that out. i had a hard time trying to use two joins and reformatting the array because the returned array would contain multiple items with the same recipe information. For example if i have one recipe with 5 ingredients, it would return five entries all the same recipe fields except the ingredients fields (id, name quantity). If this scales to alot of recipes, it wouldnt be efficient unless ur thinking about something else. Instead I kept the recipeIngredientsModel and used that function to get all the ingredients for each recipe. would that be better?

Unfortunately that is not the correct assumption.
- From efficiency standpoint, what you have right now does a database call every iteration with in the recipe array. Database itself is contained in a server which has high latency and huge overhead compare to doing an ‘N^2’ native array operation. Having 1000 recipes means calling the database 1000 times for the recipe. 
- From a cost stand point, having this amount of database call to another server is going to cost a lot(especially for services that charges you based on the amount of requests)

>  i had a hard time trying to use two joins and reformatting the array because the returned array would contain multiple items with the same recipe information

you are right about this, the returned array will contain multiple same recipe with different ingredients. We can utilize some js array native functions like filter to help us reduce the array down to only the needed stuff. Pseudo code below:

```
const recipeIngredients = await ….join function;
Await Promise.all(await recipes.map(recipe => {
  recipe.ingredientList = recipeIngredients.filter(recipeIngredient => recipeIngredient.recipeId === recipe.id);
})):
```

**Comment by joecai6** [comment]
>
> * From efficiency standpoint, what you have right now does a database call every iteration with in the recipe array. Database itself is contained in a server which has high latency and huge overhead compare to doing an ‘N^2’ native array operation. Having 1000 recipes means calling the database 1000 times for the recipe.
> * From a cost stand point, having this amount of database call to another server is going to cost a lot(especially for services that charges you based on the amount of requests)
> 

That makes sense. I didnt think about the overhead of querying. Fixed to use the filter function.

**Review by mingkaili — APPROVED** [review]

**Pull request merged**
