### PR TITLE
made new routes, get by challenge, get by spice rating

### PR DESCRIPTION
**Pull request by Cole-Rindal**
# Resolves #[add the issue number associated with your pull request here]
After creating your PR, please complete this template!

### What were your changes
[add a description of your changes here]

### What specifically should be checked
[add a description of the new functionally you added]

### CODE REVIEW

**Comment by Cole-Rindal** [comment]
image

Also made dummy recipe for testing purposes

**Comment by Cole-Rindal** [comment]
recipe-spiceRating Route test
recipe-recipeId Route test
recipe-challenge Route test
testDB

**Comment by Cole-Rindal** [comment]
Fixed all 3 routes and postman test pictures above

**Review by mingkaili — APPROVED** [review]
download

**Pull request merged**
